server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    username: root
    password: #yourPassword
    url: jdbc:mysql://localhost:3306/sharedpro #databaseName


  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true


